set(NEXTCODE_PRIMARY_VARIANT_SDK WASI CACHE STRING "")
set(NEXTCODE_PRIMARY_VARIANT_ARCH wasm32 CACHE STRING "")

set(NEXTCODE_SDKS WASI CACHE STRING "")

set(NEXTCODE_INCLUDE_TOOLS NO CACHE BOOL "")
set(NEXTCODE_INCLUDE_TESTS TRUE CACHE BOOL "")
set(NEXTCODE_INCLUDE_DOCS NO CACHE BOOL "")
set(NEXTCODE_BUILD_REMOTE_MIRROR NO CACHE BOOL "")

set(NEXTCODE_BUILD_SOURCEKIT NO CACHE BOOL "")
set(NEXTCODE_ENABLE_SOURCEKIT_TESTS NO CACHE BOOL "")

set(NEXTCODEWASM_DISABLE_REFLECTION_TEST YES CACHE BOOL "")

# stdlib configurations
set(NEXTCODE_BUILD_STATIC_STDLIB YES CACHE BOOL "")
set(NEXTCODE_BUILD_DYNAMIC_STDLIB NO CACHE BOOL "")
set(NEXTCODE_ENABLE_EXPERIMENTAL_CONCURRENCY YES CACHE BOOL "")

# build with the host compiler
set(NEXTCODE_BUILD_RUNTIME_WITH_HOST_COMPILER YES CACHE BOOL "")

set(NEXTCODE_STDLIB_SINGLE_THREADED_CONCURRENCY TRUE CACHE BOOL "")
set(NEXTCODE_THREADING_PACKAGE "none" CACHE STRING "")

set(NEXTCODE_STDLIB_SUPPORTS_BACKTRACE_REPORTING FALSE CACHE BOOL "")
set(NEXTCODE_STDLIB_HAS_DLADDR FALSE CACHE BOOL "")
set(NEXTCODE_STDLIB_COMPACT_ABSOLUTE_FUNCTION_POINTER TRUE CACHE BOOL "")
